import "./globals.css";

import { Inter, Oswald } from "next/font/google";

import Header from "@/components/sections/header";
import type { Metadata } from "next";
import Provider from "@/components/structure/provider";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin", "cyrillic"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${oswald.variable} ${inter.variable} antialiased`}>
      <body className="bg-BG">
        <Provider>
          <Header />
          {children}
        </Provider>
      </body>
    </html>
  );
}
